In [2]:
##basic library - Pandas and Numpy
import pandas as pd
import numpy as np

## Imports for Data Consistency - String Match
import difflib as dff

## Imports for different type of classfiers
from sklearn import tree # <- Decision- Trees
from sklearn import svm # <- Support Vector Machines
import sklearn.linear_model as linear_model # <- Logisitic Regression - Sigmoid Function on the Linear Regression
from sklearn.ensemble import RandomForestClassifier # <- Random Forest Classifier
from sklearn.neural_network import MLPClassifier # <- Neural Networks
from sklearn.naive_bayes import GaussianNB # <- Gaussian Naive-Bayes Classifier

## Imports for recursive feature elimination
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

## Imports for splitting the data into training and test data
from sklearn.model_selection import train_test_split

## Imports for evaluating the different classifier models selected
import sklearn.metrics as metrics
from sklearn import preprocessing

## Data Visualisation
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:


## Input the data's absolute/relative path from the user
path_excel = '/home/ad/Documents/ML Projects/h1b_visa.csv'

In [4]:


## Define the column names and read the data file into a pandas dataframe
column_names = ['CASE_STATUS', 'EMPLOYER_NAME','SOC_NAME', 'JOB_TITLE', 'FULL_TIME_POSITION', 'PREVAILING_WAGE', 'FILING_YEAR',\
               'WORKSITE', 'LONGITUDE', 'LATITUDE']
table_1 = pd.read_csv(path_excel, names = column_names, skiprows = 1, error_bad_lines = False, sep = ',')

In [5]:


pd.set_option('display.max_colwidth', -1)
pd.options.mode.chained_assignment = None

In [6]:
table_1.head()

,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,FILING_YEAR,WORKSITE,LONGITUDE,LATITUDE
1,CERTIFIED-WITHDRAWN,UNIVERSITY OF MICHIGAN,BIOCHEMISTS AND BIOPHYSICISTS,POSTDOCTORAL RESEARCH FELLOW,N,36067.0,2016.0,"ANN ARBOR, MICHIGAN",-83.743038,42.280826
2,CERTIFIED-WITHDRAWN,"GOODMAN NETWORKS, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,242674.0,2016.0,"PLANO, TEXAS",-96.698886,33.019843
3,CERTIFIED-WITHDRAWN,"PORTS AMERICA GROUP, INC.",CHIEF EXECUTIVES,CHIEF PROCESS OFFICER,Y,193066.0,2016.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
4,CERTIFIED-WITHDRAWN,"GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY OF TOMKINS PLC",CHIEF EXECUTIVES,"REGIONAL PRESIDEN, AMERICAS",Y,220314.0,2016.0,"DENVER, COLORADO",-104.990251,39.739236
5,WITHDRAWN,PEABODY INVESTMENTS CORP.,CHIEF EXECUTIVES,PRESIDENT MONGOLIA AND INDIA,Y,157518.4,2016.0,"ST. LOUIS, MISSOURI",-90.199404,38.627003

In [7]:

print(table_1['CASE_STATUS'].value_counts())

CERTIFIED                                             2615623
CERTIFIED-WITHDRAWN                                   202659
DENIED                                                94346
WITHDRAWN                                             89799
PENDING QUALITY AND COMPLIANCE REVIEW - UNASSIGNED    15
REJECTED                                              2
INVALIDATED                                           1
Name: CASE_STATUS, dtype: int64

In [8]:
table_2 = table_1.loc[table_1['CASE_STATUS'].isin(["CERTIFIED", "DENIED"])]

In [9]:
table_2

,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,FILING_YEAR,WORKSITE,LONGITUDE,LATITUDE
19,CERTIFIED,QUICKLOGIX LLC,CHIEF EXECUTIVES,CEO,Y,187200.00,2016.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
20,CERTIFIED,"MCCHRYSTAL GROUP, LLC",CHIEF EXECUTIVES,"PRESIDENT, NORTHEAST REGION",Y,241842.00,2016.0,"ALEXANDRIA, VIRGINIA",-77.046921,38.804835
23,CERTIFIED,"LOMICS, LLC",CHIEF EXECUTIVES,CEO,Y,99986.00,2016.0,"SAN DIEGO, CALIFORNIA",-117.161084,32.715738
24,CERTIFIED,UC UNIVERSITY HIGH SCHOOL EDUCATION INC.,CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,99986.00,2016.0,"CHULA VISTA, CALIFORNIA",-117.084196,32.640054
26,CERTIFIED,"QUICKLOGIX, INC.",CHIEF EXECUTIVES,CEO,Y,187200.00,2016.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
28,CERTIFIED,HELLO INC.,CHIEF EXECUTIVES,CHIEF BUSINESS OFFICER,Y,215862.00,2016.0,"SAN FRANCISCO, CALIFORNIA",-122.419415,37.774929
29,CERTIFIED,UMBEL CORP,CHIEF EXECUTIVES,VICE PRESIDENT OF ENGINEERING,Y,192088.00,2016.0,"AUSTIN, TEXAS",-97.743061,30.267153
30,CERTIFIED,"PERSPECTIVES OF FREEDOM FOUNDATION, INC",CHIEF EXECUTIVES,EXECUTIVE DIRECTOR,Y,95295.98,2016.0,"WESTON, FLORIDA",-80.399775,26.100365
31,CERTIFIED,GTH INC.,CHIEF EXECUTIVES,"VICE PRESIDENT, BUSINESS DEVELOPMENT",Y,149594.00,2016.0,"WASHINGTON, DISTRICT OF COLUMBIA",-77.036871,38.907192
32,CERTIFIED,THE KRAFT HEINZ COMPANY,CHIEF EXECUTIVES,HEAD OF US SALES,Y,226699.00,2016.0,"CHICAGO, ILLINOIS",-87.629798,41.878114
33,CERTIFIED,"REGED, INC.",CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,187200.00,2016.0,"MORRISVILLE, NORTH CAROLINA",-78.825562,35.823483
34,CERTIFIED,VMS COMMUNICATIONS LLC,CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,159370.00,2016.0,"MIAMI, FLORIDA",-80.191790,25.761680
35,CERTIFIED,"FINLAY EXTRACTS & INGREDIENTS USA, INC.",CHIEF EXECUTIVES,VICE PRESIDENT OF OPERATIONS,Y,98550.00,2016.0,"LINCOLN, RHODE ISLAND",-71.441810,41.911012
37,CERTIFIED,LABEL INSIGHT,CHIEF EXECUTIVES,CHIEF EXECUTIVE OFFICER,Y,130853.00,2016.0,"CHICAGO, ILLINOIS",-87.629798,41.878114
38,CERTIFIED,INN AT THE WICKLIFFE LLC,CHIEF EXECUTIVES,CHIEF EXECUTIVE OFFICER,N,52416.00,2016.0,"WICKLIFFE, OHIO",-81.453449,41.605327
39,CERTIFIED,"DURHAM SCHOOL SERVICES, LP",CHIEF EXECUTIVES,"VICE PRESIDENT, FINANCE AND OPERATIONS ANALYSIS",Y,130853.00,2016.0,"WARRENVILLE, ILLINOIS",-88.173402,41.817807
40,DENIED,"PARALLELS, INC.",CHIEF EXECUTIVES,CHIEF EXECUTIVE OFFICER,Y,187200.00,2016.0,"RENTON, WASHINGTON",-122.217066,47.482878
41,CERTIFIED,CB LANSING 300 LLP,CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,89107.00,2016.0,"LANSING, MICHIGAN",-84.555535,42.732535
42,CERTIFIED,"SOFTTEK INTEGRATION SYSTEMS, INC.",CHIEF EXECUTIVES,ACCOUNT DIRECTOR,Y,130853.00,2016.0,"NORTHBROOK, ILLINOIS",-87.828955,42.127527
43,CERTIFIED,"SPARITY, INC.",CHIEF EXECUTIVES,TECHNICAL DIRECTOR,Y,102190.00,2016.0,"ALPHARETTA, GEORGIA",-84.294090,34.075376
44,CERTIFIED,"ADCONION DIRECT, INC.",CHIEF EXECUTIVES,VICE PRESIDENT OF OPERATIONS,Y,197683.00,2016.0,"SOLANA BEACH, CALIFORNIA",-117.271148,32.991155
45,CERTIFIED,MAVENCARE US INC.,CHIEF EXECUTIVES,SVP BUSINESS OPERATIONS AND DEVELOPMENT,Y,122179.00,2016.0,"NEW YORK, NEW YORK",-74.005941,40.712784
46,CERTIFIED,"THE CHICAGO ATHENAEUM: CENTER FOR ARCHITECTURE, DESIGN & URBAN STUDIES",CHIEF EXECUTIVES,EXECUTIVE DIRECTOR,N,54766.00,2016.0,"GALENA, ILLINOIS",NaN,NaN
47,CERTIFIED,MED ADVANTAGE LLC,CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,187200.00,2016.0,"BLOOMFIELD, NEW JERSEY",-74.185421,40.806755
48,DENIED,RANCHO LA PUERTA LLC,CHIEF EXECUTIVES,PRESIDENT,Y,197683.20,2016.0,"SAN DIEGO, CALIFORNIA",-117.161084,32.715738
49,CERTIFIED,"STRATEGISM, INC.",CHIEF EXECUTIVES,CHIEF EXECUTIVE OFFICER,Y,155459.20,2016.0,"FREMONT, CALIFORNIA",-121.988572,37.548270
50,CERTIFIED,RANCHO LA PUERTA LLC,CHIEF EXECUTIVES,PRESIDENT,Y,197683.20,2016.0,"SAN DIEGO, CALIFORNIA",-117.161084,32.715738
51,CERTIFIED,SPRING BRANCH COMMUNITY HEALTH CENTER,CHIEF EXECUTIVES,CHIEF MEDICAL OFFICER,Y,187200.00,2016.0,"KATY, TEXAS",-95.824396,29.785785
52,CERTIFIED,SPRING BRANCH COMMUNITY HEALTH CENTER,CHIEF EXECUTIVES,CHIEF MEDICAL OFFICER,Y,187200.00,2016.0,"HOUSTON, TEXAS",-95.369803,29.760427
53,CERTIFIED,"PAXTERRA SOLUTIONS, INC.",CHIEF EXECUTIVES,"ASSISTANT VICE PRESIDENT, BUSINESS DEVELOPMENT",Y,102190.00,2016.0,"JOHNS CREEK, GEORGIA",-84.198579,34.028926
...,...,...,...,...,...,...,...,...,...,...
3002317,DENIED,MEDNET ASSOCIATES INC,"Computer Occupations, All Other*","COMPUTER OCCUPATIONS, ALL OTHER",Y,46946.00,2011.0,"WEBSTER, MASSACHUSETTS",-71.880063,42.050091
3002319,DENIED,THE CERVANTES GROUP,"Human Resources, Training, and Labor Relations Spe",RECRUITMENT ASSOCIATE,Y,29910.00,2011.0,"SAN JUAN, PUERTO RICO",-66.105735,18.465539
3002320,DENIED,"BENCHMARK FURNITURE MANUFACTURING, INC.",Management Analysts,MANAGEMENT ANALYST,Y,58531.00,2011.0,"BROOKLYN, NEW YORK",-73.944158,40.678178
3002321,DENIED,IBM CORPORATION,Management Analysts,SENIOR CONSULTANT,Y,68349.00,2011.0,"LAS VEGAS, NEVADA",-115.139830,36.169941
3002324,DENIED,"CLERYSYS, INC.",Computer Programmers,PROGRAMMER ANALYST,Y,52478.00,2011.0,"WOODCLIFF LAKE, NEW JERSEY",-74.066530,41.023430
3002327,DENIED,TECHWOOD INC,Cost Estimators,COST ESTIMATOR / PROJECT CO-ORDINATOR,Y,48090.00,2011.0,"MOUNT VERNON, NEW YORK",-73.837079,40.912599
3002328,DENIED,"SUNERA TECHNOLOGIES, INC",Computer Systems Analysts,BUSINESS PROGRAMMER ANALYST,Y,73507.00,2011.0,"HUNTERSVILLE, NORTH CAROLINA",-80.842850,35.410694
3002329,DENIED,"NORTH FLORIDA REGIONAL MEDICAL CENTER, INC.",Pharmacists,CLINICAL PHARMACIST,Y,91749.00,2011.0,"GAINESVILLE, FLORIDA",-82.324826,29.651634
3002331,DENIED,BATTELLE,Chemists,POST DOCTORATE RESEARCH ASSOCIATE,Y,47653.00,2011.0,"RICHLAND, WASHINGTON",-119.284462,46.285691
3002332,DENIED,"LANGER RESEARCH ASSOCIATES, LLC",Market Research Analysts and Marketing Specialists,RESEARCH ANALYST,Y,73174.00,2011.0,"NEW YORK, NEW YORK",-74.005941,40.712784
3002334,DENIED,"OLYMPIC COMPUTER SERVICES, INC.",Network and Computer Systems Administrators*,NETWORK AND COMPUTER SECURITY ADMINISTRATOR,N,54121.60,2011.0,"PINE BROOK, NEW JERSEY",-74.344084,40.867488
3002337,DENIED,"SUNERA TECHNOLOGIES, INC",Computer Systems Analysts,BUSINESS APPLICATIONS ANALYST,Y,63107.00,2011.0,"REDWOOD SHORES, CALIFORNIA",-122.245536,37.536413
3002340,DENIED,"HEALTHBRIDGE USA, INC.",Chief Executives,CHIEF EXECUTIVE OFFICER,Y,226325.00,2011.0,"PEACHTREE CITY, GEORGIA",-84.596343,33.396856
3002347,DENIED,"MINDTECK, INC.",Computer Programmers,COMPUTER PROGRAMMER,Y,64792.00,2011.0,"CHARLOTTE, NORTH CAROLINA",-80.843127,35.227087
3002348,DENIED,"SYNOPSYS, INC.",Network and Computer Systems Administrators*,"IT ARCHITECT, SR II",Y,94198.00,2011.0,"MOUNTAIN VIEW, CALIFORNIA",-122.083851,37.386052
3002349,DENIED,JUNG & LEE ACCOUNTANCY CORPORATION,Accountants and Auditors,ACCOUNTANT,N,59737.60,2011.0,"LOS ANGELES, CALIFORNIA",-118.243685,34.052234
3002351,DENIED,GRAYWEBGRAPHICS.COM LLC,Graphic Designers,WEB DESIGNER,Y,24856.00,2011.0,"SAN ANTONIO, TEXAS",-98.493628,29.424122
3002354,DENIED,CENTERS FOR DISEASE CONTROL AND PREVENTION/DHHS,Health Educators,RESEARCH HEALTH SPECIALIST,Y,33134.00,2011.0,"CINCINNATI, OHIO",-84.512020,39.103118
3002355,DENIED,IIDYA CORP,Computer Programmers,PROGRAMMER ANALYST,Y,43368.00,2011.0,"BEAVERTON, OREGON",-122.803710,45.487062
3002357,DENIED,IIDYA CORP,Computer Programmers,PROGRAMMER ANALYST,Y,46488.00,2011.0,"HOUSTON, TEXAS",-95.369803,29.760427
3002358,DENIED,TEJASE TECHNOLOGIES INC.,Database Administrators,DATABASE ANALYST,Y,56493.00,2011.0,"WEST DES MOINES, IOWA",-93.711332,41.577211
3002361,DENIED,ERICSSON TELEVISION INC.,"Software Developers, Systems Software",SYSTEMS MANAGER,Y,79206.00,2011.0,"DULUTH, GEORGIA",-84.144638,34.002879
3002365,DENIED,"UNIVERSITY OF CALIFORNIA, SANTA CRUZ",Biochemists and Biophysicists,POSTDOCTORAL SCHOLAR,Y,38496.00,2011.0,"SANTA CRUZ, CALIFORNIA",-122.030796,36.974117
3002367,DENIED,PARKS ASSOCIATES,Market Research Analysts and Marketing Specialists,RESEARCH ANALYST,Y,39832.00,2011.0,"DALLAS, TEXAS",-96.796988,32.776664
3002368,DENIED,OREGON HEALTH & SCIENCE UNIVERSITY,"Medical Scientists, Except Epidemiologists",SENIOR RESEARCH ASSOCIATE,Y,50357.00,2011.0,"PORTLAND, OREGON",-122.676482,45.523062
3002370,DENIED,"CUSTOMTBT, LLC",Instructional Coordinators,SENIOR INSTRUCTIONAL DESIGNER,Y,46738.00,2011.0,"MARIETTA, GEORGIA",-84.549933,33.952602
3002379,DENIED,"KEVIN PARK & ASSOCIATES, LTD",Accountants and Auditors,ACCOUNTANT,Y,45760.00,2011.0,"ARLINGTON HEIGHTS, ILLINOIS",-87.980626,42.088360
3002384,DENIED,IVERTIX INCORPORATED,Computer Programmers,APPLICATION DEVELOPER,Y,54080.00,2011.0,"WASHINGTON, DISTRICT OF COLUMBIA",-77.036871,38.907192
3002390,DENIED,"PROGRESSIVE SURFACE, INC.",Sales Engineers,SALES ENGINEER,Y,55141.00,2011.0,"GRAND RAPIDS, MICHIGAN",-85.668086,42.963360
3002393,DENIED,PEI PARTNERSHIP ARCHITECTS LLP,Architectural and Civil Drafters,ARCHITECTURAL DESIGNER,Y,69368.00,2011.0,"NEW YORK, NEW YORK",-74.005941,40.712784

In [10]:


table_2['FILING_YEAR'] = table_2['FILING_YEAR'].astype(int)
table_2['EMPLOYER_NAME'] = table_2['EMPLOYER_NAME'].str.upper()
table_2['SOC_NAME'] = table_2['SOC_NAME'].str.upper()
table_2['JOB_TITLE'] = table_2['JOB_TITLE'].str.upper()
table_2['FULL_TIME_POSITION'] = table_2['FULL_TIME_POSITION'].str.upper()#datatype conversion for the year column

In [11]:
table_2.head()

,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,FILING_YEAR,WORKSITE,LONGITUDE,LATITUDE
19,CERTIFIED,QUICKLOGIX LLC,CHIEF EXECUTIVES,CEO,Y,187200.0,2016,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
20,CERTIFIED,"MCCHRYSTAL GROUP, LLC",CHIEF EXECUTIVES,"PRESIDENT, NORTHEAST REGION",Y,241842.0,2016,"ALEXANDRIA, VIRGINIA",-77.046921,38.804835
23,CERTIFIED,"LOMICS, LLC",CHIEF EXECUTIVES,CEO,Y,99986.0,2016,"SAN DIEGO, CALIFORNIA",-117.161084,32.715738
24,CERTIFIED,UC UNIVERSITY HIGH SCHOOL EDUCATION INC.,CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,99986.0,2016,"CHULA VISTA, CALIFORNIA",-117.084196,32.640054
26,CERTIFIED,"QUICKLOGIX, INC.",CHIEF EXECUTIVES,CEO,Y,187200.0,2016,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108

In [12]:
print(table_2['CASE_STATUS'].value_counts())

CERTIFIED    2615623
DENIED       94346
Name: CASE_STATUS, dtype: int64

In [13]:
print(table_2['EMPLOYER_NAME'].value_counts().head(15))

INFOSYS LIMITED                                    130241
TATA CONSULTANCY SERVICES LIMITED                  64358
WIPRO LIMITED                                      43679
DELOITTE CONSULTING LLP                            36667
ACCENTURE LLP                                      32983
IBM INDIA PRIVATE LIMITED                          28166
MICROSOFT CORPORATION                              22373
HCL AMERICA, INC.                                  22330
ERNST & YOUNG U.S. LLP                             18217
LARSEN & TOUBRO INFOTECH LIMITED                   16724
CAPGEMINI AMERICA INC                              16032
COGNIZANT TECHNOLOGY SOLUTIONS U.S. CORPORATION    15448
GOOGLE INC.                                        12545
IGATE TECHNOLOGIES INC.                            12196
IBM CORPORATION                                    10690
Name: EMPLOYER_NAME, dtype: int64

In [14]:
print(table_2['SOC_NAME'].value_counts().head(15))

COMPUTER SYSTEMS ANALYSTS                             469300
SOFTWARE DEVELOPERS, APPLICATIONS                     372124
COMPUTER PROGRAMMERS                                  360575
COMPUTER OCCUPATIONS, ALL OTHER                       164659
SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE                 75806
MANAGEMENT ANALYSTS                                   62096
ACCOUNTANTS AND AUDITORS                              49780
FINANCIAL ANALYSTS                                    46730
MECHANICAL ENGINEERS                                  39844
NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS           36219
DATABASE ADMINISTRATORS                               35303
MARKET RESEARCH ANALYSTS AND MARKETING SPECIALISTS    34433
ELECTRONICS ENGINEERS, EXCEPT COMPUTER                31782
PHYSICIANS AND SURGEONS, ALL OTHER                    30641
OPERATIONS RESEARCH ANALYSTS                          30328
Name: SOC_NAME, dtype: int64

In [15]:
print(table_2['CASE_STATUS'].unique())

['CERTIFIED' 'DENIED']

In [16]:
table_2.isnull().sum(axis = 0)

CASE_STATUS           0
EMPLOYER_NAME         18
SOC_NAME              15893
JOB_TITLE             10
FULL_TIME_POSITION    1
PREVAILING_WAGE       53
FILING_YEAR           0
WORKSITE              0
LONGITUDE             97071
LATITUDE              97071
dtype: int64

In [17]:
table_3 = table_2.dropna(axis=0, how='any', subset = ['EMPLOYER_NAME', 'SOC_NAME', 'JOB_TITLE', 
                                                      'FULL_TIME_POSITION', 'PREVAILING_WAGE'])

In [18]:
table_3.CASE_STATUS.value_counts()

CERTIFIED    2600241
DENIED       93761
Name: CASE_STATUS, dtype: int64

In [19]:
table_temp_2_Dx = table_3[table_3['CASE_STATUS'] == 'DENIED'] #Downsampling

In [20]:
table_temp_2_Cx = table_3[table_3['CASE_STATUS'] == 'CERTIFIED']

In [27]:
Input_Certified, Input_Certified_extra, y_certified, y_certified_extra = train_test_split(table_3[table_3.CASE_STATUS == 'CERTIFIED'],\
                                                                                          table_temp_2_Cx.CASE_STATUS, train_size= 0.06, random_state=1)

In [28]:
print(Input_Certified.shape)
type(Input_Certified)

(156014, 10)

pandas.core.frame.DataFrame

In [29]:
training_dataframe = Input_Certified.append(table_temp_2_Dx)

In [30]:
training_dataframe['CASE_STATUS'].value_counts()

CERTIFIED    156014
DENIED       93761
Name: CASE_STATUS, dtype: int64

In [31]:
# one-hot encoding for every possible and needed column
print("Case Status ",training_dataframe.CASE_STATUS.nunique())
print("Unique Employers ",training_dataframe.EMPLOYER_NAME.nunique())
print("Prevailing Wages ",training_dataframe.PREVAILING_WAGE.nunique())
print("Unique SOCs ", training_dataframe.SOC_NAME.nunique())
print("Unique Job Titles ",training_dataframe.JOB_TITLE.nunique())
print("Unique Filing Year ",training_dataframe.FILING_YEAR.nunique())
print("Unique Worksite State ",training_dataframe.WORKSITE.nunique())
print("Unique Employment Type ", training_dataframe.FULL_TIME_POSITION.nunique())

Case Status  2
Unique Employers  80566
Prevailing Wages  24804
Unique SOCs  983
Unique Job Titles  53272
Unique Filing Year  6
Unique Worksite State  8637
Unique Employment Type  2

In [32]:
def wage_categorization(wage):
    if wage <=50000:
        return "VERY LOW"
    elif wage >50000 and wage <= 70000:
        return "LOW"
    elif wage >70000 and wage <= 90000:
        return "MEDIUM"
    elif wage >90000 and wage<=150000:
        return "HIGH"
    elif wage >=150000:
        return "VERY HIGH"

In [33]:
def categorisation_visagrant(ratio_of_acceptance):
    if ratio_of_acceptance == -1:
        return "AR"
    elif ratio_of_acceptance >=0.0 and ratio_of_acceptance<0.20:
        return "VLA"
    elif ratio_of_acceptance>=0.20 and ratio_of_acceptance<0.40:
        return "LA"
    elif ratio_of_acceptance>=0.40 and ratio_of_acceptance<0.60:
        return "MA"
    elif ratio_of_acceptance>=0.60 and ratio_of_acceptance<0.80:
        return "HA"
    elif ratio_of_acceptance>=0.80:
        return "VHA"

In [34]:
def state_extractor(work_site):
    return work_site.split(', ')[1]

In [35]:
training_dataframe['WORKSITE'] = training_dataframe['WORKSITE'].apply(state_extractor)

In [36]:
training_dataframe.WORKSITE.unique()

array(['PENNSYLVANIA', 'TEXAS', 'NEW YORK', 'CALIFORNIA', 'CONNECTICUT',
       'WASHINGTON', 'MISSOURI', 'OREGON', 'VIRGINIA', 'MASSACHUSETTS',
       'OHIO', 'ILLINOIS', 'FLORIDA', 'TENNESSEE', 'IDAHO', 'MARYLAND',
       'GEORGIA', 'NORTH CAROLINA', 'NEBRASKA', 'MINNESOTA', 'DELAWARE',
       'NEW HAMPSHIRE', 'ALABAMA', 'NEW JERSEY', 'WISCONSIN', 'ARIZONA',
       'INDIANA', 'MICHIGAN', 'IOWA', 'COLORADO', 'NEW MEXICO',
       'SOUTH CAROLINA', 'LOUISIANA', 'UTAH', 'KENTUCKY', 'ALASKA',
       'DISTRICT OF COLUMBIA', 'OKLAHOMA', 'ARKANSAS', 'RHODE ISLAND',
       'VERMONT', 'MAINE', 'MISSISSIPPI', 'NA', 'KANSAS', 'NEVADA',
       'HAWAII', 'WYOMING', 'PUERTO RICO', 'WEST VIRGINIA', 'MONTANA',
       'NORTH DAKOTA', 'SOUTH DAKOTA'], dtype=object)

In [37]:
training_dataframe['WAGE_CATEGORY'] = training_dataframe['PREVAILING_WAGE'].apply(wage_categorization)

In [38]:
print(training_dataframe)

        CASE_STATUS                                    EMPLOYER_NAME  \
831782   CERTIFIED   OM SHIVA ENTERPRISES INC.
139656   CERTIFIED   EPAM SYSTEMS, INC
2515170  CERTIFIED   TMH PHYSICIAN ORGANIZATION
1790210  CERTIFIED   SAP AMERICA, INC.
2628239  CERTIFIED   TOTALKARE OF AMERICA INC
1380911  CERTIFIED   FORT WORTH INDEPENDENT SCHOOL DISTRICT
2015609  CERTIFIED   GOOGLE INC.
566295   CERTIFIED   CK TECHNOLOGIES, INC.
13921    CERTIFIED   CONIFER ASSET SOLUTIONS LLC
341471   CERTIFIED   INVESTMENT METRICS, LLC
2497798  CERTIFIED   MICROSOFT CORPORATION
1176379  CERTIFIED   STRATEGIC STAFFING SOLUTIONS, L.C.
1756915  CERTIFIED   INFOSYS LIMITED
2246871  CERTIFIED   MORGAN STANLEY & CO. LLC
2189429  CERTIFIED   IBM INDIA PRIVATE LIMITED
2596568  CERTIFIED   POLARIS SOFTWARE LAB (INDIA) LTD.
2768483  CERTIFIED   NEIGHBOR COMPUTER SERVICES INC
1137310  CERTIFIED   APPLE INC.
1598011  CERTIFIED   DASSAULT SYSTEMES AMERICAS CORP
129351   CERTIFIED   WEST CORPORATION
2961630  CERTIFIED   PROTEGE, LLC
1292962  CERTIFIED   EMPYREAN BENEFITS SOLUTIONS, INC.
333545   CERTIFIED   CAPGEMINI AMERICA INC
544499   CERTIFIED   MARVELL SEMICONDUCTOR, INC.
62712    CERTIFIED   LUMINOUS SMILES PC.
1116677  CERTIFIED   INFOSYS LIMITED
277851   CERTIFIED   IDEA TECH SOLUTIONS, INC.
2333764  CERTIFIED   EMYS CAPITAL, LLC
1130305  CERTIFIED   HCA MANAGEMENT SERVICES LP
2615661  CERTIFIED   ASTIR SERVICES LLC
...            ...                  ...
3002317  DENIED      MEDNET ASSOCIATES INC
3002319  DENIED      THE CERVANTES GROUP
3002320  DENIED      BENCHMARK FURNITURE MANUFACTURING, INC.
3002321  DENIED      IBM CORPORATION
3002324  DENIED      CLERYSYS, INC.
3002327  DENIED      TECHWOOD INC
3002328  DENIED      SUNERA TECHNOLOGIES, INC
3002329  DENIED      NORTH FLORIDA REGIONAL MEDICAL CENTER, INC.
3002331  DENIED      BATTELLE
3002332  DENIED      LANGER RESEARCH ASSOCIATES, LLC
3002334  DENIED      OLYMPIC COMPUTER SERVICES, INC.
3002337  DENIED      SUNERA TECHNOLOGIES, INC
3002340  DENIED      HEALTHBRIDGE USA, INC.
3002347  DENIED      MINDTECK, INC.
3002348  DENIED      SYNOPSYS, INC.
3002349  DENIED      JUNG & LEE ACCOUNTANCY CORPORATION
3002351  DENIED      GRAYWEBGRAPHICS.COM LLC
3002354  DENIED      CENTERS FOR DISEASE CONTROL AND PREVENTION/DHHS
3002355  DENIED      IIDYA CORP
3002357  DENIED      IIDYA CORP
3002358  DENIED      TEJASE TECHNOLOGIES INC.
3002361  DENIED      ERICSSON TELEVISION INC.
3002365  DENIED      UNIVERSITY OF CALIFORNIA, SANTA CRUZ
3002367  DENIED      PARKS ASSOCIATES
3002368  DENIED      OREGON HEALTH & SCIENCE UNIVERSITY
3002370  DENIED      CUSTOMTBT, LLC
3002379  DENIED      KEVIN PARK & ASSOCIATES, LTD
3002384  DENIED      IVERTIX INCORPORATED
3002390  DENIED      PROGRESSIVE SURFACE, INC.
3002393  DENIED      PEI PARTNERSHIP ARCHITECTS LLP

                                                   SOC_NAME  \
831782   ELECTRONICS ENGINEERS, EXCEPT COMPUTER
139656   COMPUTER SYSTEMS ANALYSTS
2515170  HEALTH DIAGNOSING AND TREATING PRACTITIONERS, ALL
1790210  COMPUTER SYSTEMS ANALYSTS
2628239  GENERAL AND OPERATIONS MANAGERS
1380911  ELEMENTARY SCHOOL TEACHERS, EXCEPT SPECIAL EDUCATI
2015609  SOFTWARE DEVELOPERS, APPLICATIONS
566295   ENGINEERS, ALL OTHER
13921    FINANCIAL MANAGERS
341471   SOFTWARE DEVELOPERS, APPLICATIONS
2497798  COMPUTER OCCUPATIONS, ALL OTHER*
1176379  SOFTWARE DEVELOPERS, APPLICATIONS
1756915  COMPUTER PROGRAMMERS
2246871  COMPUTER SYSTEMS ANALYSTS
2189429  COMPUTER PROGRAMMERS
2596568  COMPUTER SYSTEMS ANALYSTS
2768483  COMPUTER SYSTEMS ANALYSTS
1137310  MATERIALS ENGINEERS
1598011  SOFTWARE DEVELOPERS, APPLICATIONS
129351   COMPUTER SYSTEMS ANALYSTS
2961630  COMPUTER SYSTEMS ANALYSTS
1292962  OPERATIONS RESEARCH ANALYSTS
333545   SOFTWARE DEVELOPERS, APPLICATIONS
544499   ELECTRONICS ENGINEERS, EXCEPT COMPUTER
62712    ACCOUNTANTS AND AUDITORS
1116677  COMPUTER OCCUPATIONS, ALL OTHER
277851   COMPUTER PROGRAMMERS
2333764  FINANCIAL ANALYSTS
1130305  SOFTWARE DEVELOPERS, APPLICATIONS
2615661  COMPUTER SYSTEMS ANALYSTS
...                            ...
3002317  COMPUTER OCCUPATIONS, ALL OTHER*
3002319  HUMAN RESOURCES, TRAINING, AND LABOR RELATIONS SPE
3002320  MANAGEMENT ANALYSTS
3002321  MANAGEMENT ANALYSTS
3002324  COMPUTER PROGRAMMERS
3002327  COST ESTIMATORS
3002328  COMPUTER SYSTEMS ANALYSTS
3002329  PHARMACISTS
3002331  CHEMISTS
3002332  MARKET RESEARCH ANALYSTS AND MARKETING SPECIALISTS
3002334  NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS*
3002337  COMPUTER SYSTEMS ANALYSTS
3002340  CHIEF EXECUTIVES
3002347  COMPUTER PROGRAMMERS
3002348  NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS*
3002349  ACCOUNTANTS AND AUDITORS
3002351  GRAPHIC DESIGNERS
3002354  HEALTH EDUCATORS
3002355  COMPUTER PROGRAMMERS
3002357  COMPUTER PROGRAMMERS
3002358  DATABASE ADMINISTRATORS
3002361  SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE
3002365  BIOCHEMISTS AND BIOPHYSICISTS
3002367  MARKET RESEARCH ANALYSTS AND MARKETING SPECIALISTS
3002368  MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS
3002370  INSTRUCTIONAL COORDINATORS
3002379  ACCOUNTANTS AND AUDITORS
3002384  COMPUTER PROGRAMMERS
3002390  SALES ENGINEERS
3002393  ARCHITECTURAL AND CIVIL DRAFTERS

                                           JOB_TITLE FULL_TIME_POSITION  \
831782   ELECTRONIC AND COMMUNICATION ENGINEER        Y
139656   LEAD BUSINESS ANALYST                        Y
2515170  RESIDENT OB/GYN                              Y
1790210  BUSINESS PROCESS SENIOR CONSULTANT           Y
2628239  DIRECTOR OF OPERATIONS                       Y
1380911  ELEMENTARY BILINGUAL TEACHER                 Y
2015609  SOFTWARE ENGINEER                            Y
566295   ASSOCIATE ENGINEER                           N
13921    DIRECTOR - PROJECT MANAGEMENT                Y
341471   SOFTWARE DEVELOPMENT ENGINEER                N
2497798  UX RESEARCHER                                Y
1176379  SENIOR .NET DEVELOPER                        Y
1756915  SYSTEMS ENGINEER - US                        Y
2246871  VICE PRESIDENT, TECHNOLOGY                   Y
2189429  APPLICATION DEVELOPER                        Y
2596568  SYSTEMS ANALYST                              Y
2768483  PROGRAMMER ANALYST                           Y
1137310  PRODUCT DESIGN ENGINEER 5                    Y
1598011  SOFTWARE DEVELOPMENT ENGINEER                Y
129351   SOFTWARE ANALYST                             N
2961630  SOFTWARE TEST ANALYST                        Y
1292962  OPERATIONS MANAGER                           Y
333545   SOFTWARE ENGINEER                            Y
544499   VALIDATION ENGINEER                          Y
62712    ACCOUNTING                                   N
1116677  SENIOR TECHNOLOGY ARCHITECT - US             Y
277851   PROGRAMMER ANALYST                           N
2333764  RESEARCH ANALYST                             N
1130305  SR. APPLICATION ENGINEER                     Y
2615661  COMPUTER SYSTEM ANALYST                      Y
...                          ...                     ..
3002317  COMPUTER OCCUPATIONS, ALL OTHER              Y
3002319  RECRUITMENT ASSOCIATE                        Y
3002320  MANAGEMENT ANALYST                           Y
3002321  SENIOR CONSULTANT                            Y
3002324  PROGRAMMER ANALYST                           Y
3002327  COST ESTIMATOR / PROJECT CO-ORDINATOR        Y
3002328  BUSINESS PROGRAMMER ANALYST                  Y
3002329  CLINICAL PHARMACIST                          Y
3002331  POST DOCTORATE RESEARCH ASSOCIATE            Y
3002332  RESEARCH ANALYST                             Y
3002334  NETWORK AND COMPUTER SECURITY ADMINISTRATOR  N
3002337  BUSINESS APPLICATIONS ANALYST                Y
3002340  CHIEF EXECUTIVE OFFICER                      Y
3002347  COMPUTER PROGRAMMER                          Y
3002348  IT ARCHITECT, SR II                          Y
3002349  ACCOUNTANT                                   N
3002351  WEB DESIGNER                                 Y
3002354  RESEARCH HEALTH SPECIALIST                   Y
3002355  PROGRAMMER ANALYST                           Y
3002357  PROGRAMMER ANALYST                           Y
3002358  DATABASE ANALYST                             Y
3002361  SYSTEMS MANAGER                              Y
3002365  POSTDOCTORAL SCHOLAR                         Y
3002367  RESEARCH ANALYST                             Y
3002368  SENIOR RESEARCH ASSOCIATE                    Y
3002370  SENIOR INSTRUCTIONAL DESIGNER                Y
3002379  ACCOUNTANT                                   Y
3002384  APPLICATION DEVELOPER                        Y
3002390  SALES ENGINEER                               Y
3002393  ARCHITECTURAL DESIGNER                       Y

         PREVAILING_WAGE  FILING_YEAR              WORKSITE   LONGITUDE  \
831782   56118.0          2015         PENNSYLVANIA         NaN
139656   77147.0          2016         PENNSYLVANIA         -75.165222
2515170  47033.0          2012         TEXAS                -95.369803
1790210  84282.0          2013         PENNSYLVANIA         -75.400706
2628239  56992.0          2012         NEW YORK             -76.147424
1380911  45190.0          2014         TEXAS                -97.330766
2015609  100984.0         2013         CALIFORNIA           -122.083851
566295   52645.0          2016         CALIFORNIA           -119.037602
13921    99050.0          2016         CALIFORNIA           -122.419415
341471   69680.0          2016         CONNECTICUT          -73.468686
2497798  69389.0          2012         WASHINGTON           -122.121512
1176379  108056.0         2015         MISSOURI             -90.577067
1756915  47008.0          2014         OREGON               -122.803710
2246871  89939.0          2012         NEW YORK             -74.005941
2189429  67558.0          2013         VIRGINIA             -77.357003
2596568  55182.0          2012         PENNSYLVANIA         -75.370458
2768483  59613.0          2011         NEW YORK             -73.732631
1137310  104832.0         2015         CALIFORNIA           -122.032182
1598011  88296.0          2014         MASSACHUSETTS        -71.235611
129351   53914.0          2016         OHIO                 -83.114077
2961630  56347.0          2011         VIRGINIA             -77.357003
1292962  63960.0          2014         TEXAS                -95.369803
333545   73008.0          2016         ILLINOIS             -88.993687
544499   88176.0          2016         CALIFORNIA           -121.955236
62712    47028.8          2016         PENNSYLVANIA         NaN
1116677  100734.0         2015         TEXAS                -97.743061
277851   63024.0          2016         FLORIDA              -82.457178
2333764  62566.4          2012         NEW YORK             -74.005941
1130305  81286.0          2015         TENNESSEE            -86.782777
2615661  74880.0          2012         CALIFORNIA           -118.614810
...          ...           ...                ...                   ...
3002317  46946.0          2011         MASSACHUSETTS        -71.880063
3002319  29910.0          2011         PUERTO RICO          -66.105735
3002320  58531.0          2011         NEW YORK             -73.944158
3002321  68349.0          2011         NEVADA               -115.139830
3002324  52478.0          2011         NEW JERSEY           -74.066530
3002327  48090.0          2011         NEW YORK             -73.837079
3002328  73507.0          2011         NORTH CAROLINA       -80.842850
3002329  91749.0          2011         FLORIDA              -82.324826
3002331  47653.0          2011         WASHINGTON           -119.284462
3002332  73174.0          2011         NEW YORK             -74.005941
3002334  54121.6          2011         NEW JERSEY           -74.344084
3002337  63107.0          2011         CALIFORNIA           -122.245536
3002340  226325.0         2011         GEORGIA              -84.596343
3002347  64792.0          2011         NORTH CAROLINA       -80.843127
3002348  94198.0          2011         CALIFORNIA           -122.083851
3002349  59737.6          2011         CALIFORNIA           -118.243685
3002351  24856.0          2011         TEXAS                -98.493628
3002354  33134.0          2011         OHIO                 -84.512020
3002355  43368.0          2011         OREGON               -122.803710
3002357  46488.0          2011         TEXAS                -95.369803
3002358  56493.0          2011         IOWA                 -93.711332
3002361  79206.0          2011         GEORGIA              -84.144638
3002365  38496.0          2011         CALIFORNIA           -122.030796
3002367  39832.0          2011         TEXAS                -96.796988
3002368  50357.0          2011         OREGON               -122.676482
3002370  46738.0          2011         GEORGIA              -84.549933
3002379  45760.0          2011         ILLINOIS             -87.980626
3002384  54080.0          2011         DISTRICT OF COLUMBIA -77.036871
3002390  55141.0          2011         MICHIGAN             -85.668086
3002393  69368.0          2011         NEW YORK             -74.005941

          LATITUDE WAGE_CATEGORY
831782  NaN         LOW
139656   39.952584  MEDIUM
2515170  29.760427  VERY LOW
1790210  39.986890  MEDIUM
2628239  43.048122  LOW
1380911  32.755488  VERY LOW
2015609  37.386052  HIGH
566295   34.216394  LOW
13921    37.774929  HIGH
341471   41.077191  LOW
2497798  47.673988  LOW
1176379  38.663108  HIGH
1756915  45.487062  VERY LOW
2246871  40.712784  MEDIUM
2189429  38.958631  LOW
2596568  40.625932  LOW
2768483  40.948710  LOW
1137310  37.322998  HIGH
1598011  42.376485  MEDIUM
129351   40.099229  LOW
2961630  38.958631  LOW
1292962  29.760427  LOW
333545   40.484203  MEDIUM
544499   37.354108  MEDIUM
62712   NaN         VERY LOW
1116677  30.267153  HIGH
277851   27.950575  LOW
2333764  40.712784  LOW
1130305  36.033116  MEDIUM
2615661  34.250636  MEDIUM
...            ...     ...
3002317  42.050091  VERY LOW
3002319  18.465539  VERY LOW
3002320  40.678178  LOW
3002321  36.169941  LOW
3002324  41.023430  LOW
3002327  40.912599  VERY LOW
3002328  35.410694  MEDIUM
3002329  29.651634  HIGH
3002331  46.285691  VERY LOW
3002332  40.712784  MEDIUM
3002334  40.867488  LOW
3002337  37.536413  LOW
3002340  33.396856  VERY HIGH
3002347  35.227087  LOW
3002348  37.386052  HIGH
3002349  34.052234  LOW
3002351  29.424122  VERY LOW
3002354  39.103118  VERY LOW
3002355  45.487062  VERY LOW
3002357  29.760427  VERY LOW
3002358  41.577211  LOW
3002361  34.002879  MEDIUM
3002365  36.974117  VERY LOW
3002367  32.776664  VERY LOW
3002368  45.523062  LOW
3002370  33.952602  VERY LOW
3002379  42.088360  VERY LOW
3002384  38.907192  LOW
3002390  42.963360  LOW
3002393  40.712784  LOW

[249775 rows x 11 columns]

In [39]:
training_dataframe_1 = training_dataframe.loc[:,['EMPLOYER_NAME', 'CASE_STATUS']]
training_dataframe_1s = training_dataframe.loc[:,['SOC_NAME', 'CASE_STATUS']]
training_dataframe_1j = training_dataframe.loc[:,['JOB_TITLE', 'CASE_STATUS']]

In [40]:
print(training_dataframe_1)

                                           EMPLOYER_NAME CASE_STATUS
831782   OM SHIVA ENTERPRISES INC.                        CERTIFIED
139656   EPAM SYSTEMS, INC                                CERTIFIED
2515170  TMH PHYSICIAN ORGANIZATION                       CERTIFIED
1790210  SAP AMERICA, INC.                                CERTIFIED
2628239  TOTALKARE OF AMERICA INC                         CERTIFIED
1380911  FORT WORTH INDEPENDENT SCHOOL DISTRICT           CERTIFIED
2015609  GOOGLE INC.                                      CERTIFIED
566295   CK TECHNOLOGIES, INC.                            CERTIFIED
13921    CONIFER ASSET SOLUTIONS LLC                      CERTIFIED
341471   INVESTMENT METRICS, LLC                          CERTIFIED
2497798  MICROSOFT CORPORATION                            CERTIFIED
1176379  STRATEGIC STAFFING SOLUTIONS, L.C.               CERTIFIED
1756915  INFOSYS LIMITED                                  CERTIFIED
2246871  MORGAN STANLEY & CO. LLC                         CERTIFIED
2189429  IBM INDIA PRIVATE LIMITED                        CERTIFIED
2596568  POLARIS SOFTWARE LAB (INDIA) LTD.                CERTIFIED
2768483  NEIGHBOR COMPUTER SERVICES INC                   CERTIFIED
1137310  APPLE INC.                                       CERTIFIED
1598011  DASSAULT SYSTEMES AMERICAS CORP                  CERTIFIED
129351   WEST CORPORATION                                 CERTIFIED
2961630  PROTEGE, LLC                                     CERTIFIED
1292962  EMPYREAN BENEFITS SOLUTIONS, INC.                CERTIFIED
333545   CAPGEMINI AMERICA INC                            CERTIFIED
544499   MARVELL SEMICONDUCTOR, INC.                      CERTIFIED
62712    LUMINOUS SMILES PC.                              CERTIFIED
1116677  INFOSYS LIMITED                                  CERTIFIED
277851   IDEA TECH SOLUTIONS, INC.                        CERTIFIED
2333764  EMYS CAPITAL, LLC                                CERTIFIED
1130305  HCA MANAGEMENT SERVICES LP                       CERTIFIED
2615661  ASTIR SERVICES LLC                               CERTIFIED
...                     ...                                     ...
3002317  MEDNET ASSOCIATES INC                            DENIED
3002319  THE CERVANTES GROUP                              DENIED
3002320  BENCHMARK FURNITURE MANUFACTURING, INC.          DENIED
3002321  IBM CORPORATION                                  DENIED
3002324  CLERYSYS, INC.                                   DENIED
3002327  TECHWOOD INC                                     DENIED
3002328  SUNERA TECHNOLOGIES, INC                         DENIED
3002329  NORTH FLORIDA REGIONAL MEDICAL CENTER, INC.      DENIED
3002331  BATTELLE                                         DENIED
3002332  LANGER RESEARCH ASSOCIATES, LLC                  DENIED
3002334  OLYMPIC COMPUTER SERVICES, INC.                  DENIED
3002337  SUNERA TECHNOLOGIES, INC                         DENIED
3002340  HEALTHBRIDGE USA, INC.                           DENIED
3002347  MINDTECK, INC.                                   DENIED
3002348  SYNOPSYS, INC.                                   DENIED
3002349  JUNG & LEE ACCOUNTANCY CORPORATION               DENIED
3002351  GRAYWEBGRAPHICS.COM LLC                          DENIED
3002354  CENTERS FOR DISEASE CONTROL AND PREVENTION/DHHS  DENIED
3002355  IIDYA CORP                                       DENIED
3002357  IIDYA CORP                                       DENIED
3002358  TEJASE TECHNOLOGIES INC.                         DENIED
3002361  ERICSSON TELEVISION INC.                         DENIED
3002365  UNIVERSITY OF CALIFORNIA, SANTA CRUZ             DENIED
3002367  PARKS ASSOCIATES                                 DENIED
3002368  OREGON HEALTH & SCIENCE UNIVERSITY               DENIED
3002370  CUSTOMTBT, LLC                                   DENIED
3002379  KEVIN PARK & ASSOCIATES, LTD                     DENIED
3002384  IVERTIX INCORPORATED                             DENIED
3002390  PROGRESSIVE SURFACE, INC.                        DENIED
3002393  PEI PARTNERSHIP ARCHITECTS LLP                   DENIED

[249775 rows x 2 columns]

In [41]:
print(training_dataframe_1s)

                                                   SOC_NAME CASE_STATUS
831782   ELECTRONICS ENGINEERS, EXCEPT COMPUTER              CERTIFIED
139656   COMPUTER SYSTEMS ANALYSTS                           CERTIFIED
2515170  HEALTH DIAGNOSING AND TREATING PRACTITIONERS, ALL   CERTIFIED
1790210  COMPUTER SYSTEMS ANALYSTS                           CERTIFIED
2628239  GENERAL AND OPERATIONS MANAGERS                     CERTIFIED
1380911  ELEMENTARY SCHOOL TEACHERS, EXCEPT SPECIAL EDUCATI  CERTIFIED
2015609  SOFTWARE DEVELOPERS, APPLICATIONS                   CERTIFIED
566295   ENGINEERS, ALL OTHER                                CERTIFIED
13921    FINANCIAL MANAGERS                                  CERTIFIED
341471   SOFTWARE DEVELOPERS, APPLICATIONS                   CERTIFIED
2497798  COMPUTER OCCUPATIONS, ALL OTHER*                    CERTIFIED
1176379  SOFTWARE DEVELOPERS, APPLICATIONS                   CERTIFIED
1756915  COMPUTER PROGRAMMERS                                CERTIFIED
2246871  COMPUTER SYSTEMS ANALYSTS                           CERTIFIED
2189429  COMPUTER PROGRAMMERS                                CERTIFIED
2596568  COMPUTER SYSTEMS ANALYSTS                           CERTIFIED
2768483  COMPUTER SYSTEMS ANALYSTS                           CERTIFIED
1137310  MATERIALS ENGINEERS                                 CERTIFIED
1598011  SOFTWARE DEVELOPERS, APPLICATIONS                   CERTIFIED
129351   COMPUTER SYSTEMS ANALYSTS                           CERTIFIED
2961630  COMPUTER SYSTEMS ANALYSTS                           CERTIFIED
1292962  OPERATIONS RESEARCH ANALYSTS                        CERTIFIED
333545   SOFTWARE DEVELOPERS, APPLICATIONS                   CERTIFIED
544499   ELECTRONICS ENGINEERS, EXCEPT COMPUTER              CERTIFIED
62712    ACCOUNTANTS AND AUDITORS                            CERTIFIED
1116677  COMPUTER OCCUPATIONS, ALL OTHER                     CERTIFIED
277851   COMPUTER PROGRAMMERS                                CERTIFIED
2333764  FINANCIAL ANALYSTS                                  CERTIFIED
1130305  SOFTWARE DEVELOPERS, APPLICATIONS                   CERTIFIED
2615661  COMPUTER SYSTEMS ANALYSTS                           CERTIFIED
...                            ...                                 ...
3002317  COMPUTER OCCUPATIONS, ALL OTHER*                    DENIED
3002319  HUMAN RESOURCES, TRAINING, AND LABOR RELATIONS SPE  DENIED
3002320  MANAGEMENT ANALYSTS                                 DENIED
3002321  MANAGEMENT ANALYSTS                                 DENIED
3002324  COMPUTER PROGRAMMERS                                DENIED
3002327  COST ESTIMATORS                                     DENIED
3002328  COMPUTER SYSTEMS ANALYSTS                           DENIED
3002329  PHARMACISTS                                         DENIED
3002331  CHEMISTS                                            DENIED
3002332  MARKET RESEARCH ANALYSTS AND MARKETING SPECIALISTS  DENIED
3002334  NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS*        DENIED
3002337  COMPUTER SYSTEMS ANALYSTS                           DENIED
3002340  CHIEF EXECUTIVES                                    DENIED
3002347  COMPUTER PROGRAMMERS                                DENIED
3002348  NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS*        DENIED
3002349  ACCOUNTANTS AND AUDITORS                            DENIED
3002351  GRAPHIC DESIGNERS                                   DENIED
3002354  HEALTH EDUCATORS                                    DENIED
3002355  COMPUTER PROGRAMMERS                                DENIED
3002357  COMPUTER PROGRAMMERS                                DENIED
3002358  DATABASE ADMINISTRATORS                             DENIED
3002361  SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE               DENIED
3002365  BIOCHEMISTS AND BIOPHYSICISTS                       DENIED
3002367  MARKET RESEARCH ANALYSTS AND MARKETING SPECIALISTS  DENIED
3002368  MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS          DENIED
3002370  INSTRUCTIONAL COORDINATORS                          DENIED
3002379  ACCOUNTANTS AND AUDITORS                            DENIED
3002384  COMPUTER PROGRAMMERS                                DENIED
3002390  SALES ENGINEERS                                     DENIED
3002393  ARCHITECTURAL AND CIVIL DRAFTERS                    DENIED

[249775 rows x 2 columns]

In [42]:
training_dataframe_2_C = training_dataframe_1[training_dataframe_1.CASE_STATUS == 'CERTIFIED'].EMPLOYER_NAME
training_dataframe_2_Cs = training_dataframe_1s[training_dataframe_1s.CASE_STATUS == 'CERTIFIED'].SOC_NAME
training_dataframe_2_Cj = training_dataframe_1j[training_dataframe_1j.CASE_STATUS == 'CERTIFIED'].JOB_TITLE
positive_counts = training_dataframe_2_C.value_counts()
positive_counts_s = training_dataframe_2_Cs.value_counts()
positive_counts_j = training_dataframe_2_Cj.value_counts()

In [43]:
total_counts = training_dataframe_1.EMPLOYER_NAME.value_counts()
total_counts_s = training_dataframe_1s.SOC_NAME.value_counts()
total_counts_j = training_dataframe_1j.JOB_TITLE.value_counts()

In [44]:
final_ratio_series = positive_counts / total_counts

final_ratio_series.fillna(-1, inplace=True)
final_classification_employer = final_ratio_series.apply(categorisation_visagrant)
training_dataframe['EMPLOYER_ACCEPTANCE'] = training_dataframe.EMPLOYER_NAME.map(final_classification_employer)

In [45]:
final_ratio_series_s = positive_counts_s / total_counts_s
final_ratio_series_s.fillna(-1, inplace=True)
final_classification_soc = final_ratio_series_s.apply(categorisation_visagrant)
training_dataframe['SOC_ACCEPTANCE'] = training_dataframe.SOC_NAME.map(final_classification_soc)

In [46]:
final_ratio_series_j = positive_counts_j / total_counts_j
final_ratio_series_j.fillna(-1, inplace=True)
final_classification_job = final_ratio_series_j.apply(categorisation_visagrant)
training_dataframe['JOB_ACCEPTANCE'] = training_dataframe.JOB_TITLE.map(final_classification_job)

In [47]:
print("Case Status ",training_dataframe.CASE_STATUS.nunique())
print("Unique Employers ",training_dataframe.EMPLOYER_ACCEPTANCE.nunique())
print("Wages Category", training_dataframe.WAGE_CATEGORY.nunique())
print("Unique SOCs ", training_dataframe.SOC_ACCEPTANCE.nunique())
print("Unique Job Titles ",training_dataframe.JOB_ACCEPTANCE.nunique())
print("Unique Filing Year ",training_dataframe.FILING_YEAR.nunique())
print("Unique Worksite State ",training_dataframe.WORKSITE.nunique())
print("Unique Employment Type ", training_dataframe.FULL_TIME_POSITION.nunique())

Case Status  2
Unique Employers  6
Wages Category 5
Unique SOCs  6
Unique Job Titles  6
Unique Filing Year  6
Unique Worksite State  53
Unique Employment Type  2

In [48]:
dict_cs = {"CERTIFIED" : 1, "DENIED": 0}
dict_fp = {"Y" : 1, "N" : 0}
try:
    
    training_dataframe['CASE_STATUS'] = training_dataframe['CASE_STATUS'].apply(lambda x: dict_cs[x])
    training_dataframe['FULL_TIME_POSITION'] = training_dataframe['FULL_TIME_POSITION'].apply(lambda x: dict_fp[x])
except:
    pass

In [49]:
training_dataframe['FILING_YEAR'] = training_dataframe['FILING_YEAR'].astype('int')
training_dataframe.sort_index(inplace = True)
training_dataframe = training_dataframe.loc[:, ['CASE_STATUS', 'FILING_YEAR',\
                                                'WORKSITE', 'WAGE_CATEGORY',  'EMPLOYER_ACCEPTANCE', 'JOB_ACCEPTANCE', 'SOC_ACCEPTANCE', 'FULL_TIME_POSITION']]
training_dataframe.head()

,CASE_STATUS,FILING_YEAR,WORKSITE,WAGE_CATEGORY,EMPLOYER_ACCEPTANCE,JOB_ACCEPTANCE,SOC_ACCEPTANCE,FULL_TIME_POSITION
40,0,2016,WASHINGTON,VERY HIGH,AR,LA,LA,1
48,0,2016,CALIFORNIA,VERY HIGH,AR,LA,LA,1
67,1,2016,GEORGIA,VERY HIGH,VHA,LA,LA,1
71,1,2016,PENNSYLVANIA,VERY HIGH,VHA,LA,LA,1
92,0,2016,MICHIGAN,HIGH,AR,VLA,LA,1

In [50]:
final_df_train = pd.get_dummies(training_dataframe, columns=['FILING_YEAR', 'WORKSITE', 'FULL_TIME_POSITION', 'WAGE_CATEGORY', 'EMPLOYER_ACCEPTANCE',
                                                             
                                                                'JOB_ACCEPTANCE', 'SOC_ACCEPTANCE' ], drop_first=True)
final_df_train.head()

,CASE_STATUS,FILING_YEAR_2012,FILING_YEAR_2013,FILING_YEAR_2014,FILING_YEAR_2015,FILING_YEAR_2016,WORKSITE_ALASKA,WORKSITE_ARIZONA,WORKSITE_ARKANSAS,WORKSITE_CALIFORNIA,...,JOB_ACCEPTANCE_HA,JOB_ACCEPTANCE_LA,JOB_ACCEPTANCE_MA,JOB_ACCEPTANCE_VHA,JOB_ACCEPTANCE_VLA,SOC_ACCEPTANCE_HA,SOC_ACCEPTANCE_LA,SOC_ACCEPTANCE_MA,SOC_ACCEPTANCE_VHA,SOC_ACCEPTANCE_VLA
40,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
48,0,0,0,0,0,1,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
67,1,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
71,1,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
92,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0

In [51]:
model = LogisticRegression()
rfe = RFE(model, 30)
fit = rfe.fit(final_df_train.iloc[:,1:], final_df_train.iloc[:,0])
support_rfe = rfe.support_
length_cols = list(final_df_train.iloc[:,1:].columns.values)
list_selected = []
for index in range(len(length_cols)):
    if support_rfe[index] == True:
        list_selected.append(length_cols[index])
    else:
        pass
print(list_selected)
print(rfe.ranking_)     # ref.ranking_ returns an array with positive integer values 
                         # to indicate the attribute ranking with a lower score indicating a higher ranking

/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ad/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

['FILING_YEAR_2012', 'FILING_YEAR_2013', 'FILING_YEAR_2014', 'FILING_YEAR_2015', 'FILING_YEAR_2016', 'WORKSITE_COLORADO', 'WORKSITE_DISTRICT OF COLUMBIA', 'WORKSITE_MAINE', 'WORKSITE_MISSISSIPPI', 'WORKSITE_NA', 'WORKSITE_NEW MEXICO', 'WORKSITE_NORTH DAKOTA', 'WORKSITE_OKLAHOMA', 'WORKSITE_SOUTH DAKOTA', 'FULL_TIME_POSITION_1', 'WAGE_CATEGORY_VERY HIGH', 'EMPLOYER_ACCEPTANCE_HA', 'EMPLOYER_ACCEPTANCE_LA', 'EMPLOYER_ACCEPTANCE_MA', 'EMPLOYER_ACCEPTANCE_VHA', 'EMPLOYER_ACCEPTANCE_VLA', 'JOB_ACCEPTANCE_HA', 'JOB_ACCEPTANCE_LA', 'JOB_ACCEPTANCE_MA', 'JOB_ACCEPTANCE_VHA', 'JOB_ACCEPTANCE_VLA', 'SOC_ACCEPTANCE_LA', 'SOC_ACCEPTANCE_MA', 'SOC_ACCEPTANCE_VHA', 'SOC_ACCEPTANCE_VLA']
[ 1  1  1  1  1 34 30 39 20  1 13 29  1 43  5 40 14 31 38 46 37 32 22  1
 15 12 17 24  1 18  8  1 42  7 36 23  1 28  6  1 25  1 44 11 19 35 48  1
 26 16 21  4  9  3 41 45 10  1 33 47  1  2  1  1  1  1  1  1  1  1  1  1
 27  1  1  1  1]

In [52]:
unique_listcols = [col.split('_')[0] for col in list_selected]
set(unique_listcols)

{'EMPLOYER', 'FILING', 'FULL', 'JOB', 'SOC', 'WAGE', 'WORKSITE'}

In [53]:
X_train, X_test, y_train, y_test = train_test_split(final_df_train.iloc[:,1:], final_df_train.iloc[:, 0], test_size = 0.20, random_state=1)
#y_train[y_train==1].shape
y_test[y_test==1].shape

(31200,)

In [54]:
X_train.head()

,FILING_YEAR_2012,FILING_YEAR_2013,FILING_YEAR_2014,FILING_YEAR_2015,FILING_YEAR_2016,WORKSITE_ALASKA,WORKSITE_ARIZONA,WORKSITE_ARKANSAS,WORKSITE_CALIFORNIA,WORKSITE_COLORADO,...,JOB_ACCEPTANCE_HA,JOB_ACCEPTANCE_LA,JOB_ACCEPTANCE_MA,JOB_ACCEPTANCE_VHA,JOB_ACCEPTANCE_VLA,SOC_ACCEPTANCE_HA,SOC_ACCEPTANCE_LA,SOC_ACCEPTANCE_MA,SOC_ACCEPTANCE_VHA,SOC_ACCEPTANCE_VLA
363035,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
2794145,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
2298634,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
256431,0,0,0,0,1,0,0,0,1,0,...,1,0,0,0,0,1,0,0,0,0
2924320,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0

In [55]:
dtree = tree.DecisionTreeClassifier()
dtree = dtree.fit(X_train, y_train)

In [56]:
y_pred = dtree.predict(X_test)

y_prob = dtree.predict_proba(X_test)

print("test", y_test[:10])
print("pred", y_pred[:10])
print()

print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.classification_report(y_test, y_pred))

test 1069288    1
608356     0
873558     1
2063900    0
879489     1
2280958    1
564763     0
2784494    1
2531142    1
718034     0
Name: CASE_STATUS, dtype: int64
pred [1 0 1 0 1 1 0 1 1 1]

[[14832  3923]
 [ 2226 28974]]
              precision    recall  f1-score   support

           0       0.87      0.79      0.83     18755
           1       0.88      0.93      0.90     31200

   micro avg       0.88      0.88      0.88     49955
   macro avg       0.88      0.86      0.87     49955
weighted avg       0.88      0.88      0.88     49955

In [57]:
mlp = MLPClassifier(hidden_layer_sizes=(20,20,20,20,20), max_iter=1000)
mlp.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(20, 20, 20, 20, 20), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [58]:
y_pred_mlp = mlp.predict(X_test)
confusion = metrics.confusion_matrix(y_test, y_pred_mlp)
print(confusion)
print(metrics.classification_report(y_test, y_pred_mlp))
#print(metrics.recall_score(y_test, y_pred))
#print(metrics.f1_score(y_test, y_pred))

[[14640  4115]
 [ 1335 29865]]
              precision    recall  f1-score   support

           0       0.92      0.78      0.84     18755
           1       0.88      0.96      0.92     31200

   micro avg       0.89      0.89      0.89     49955
   macro avg       0.90      0.87      0.88     49955
weighted avg       0.89      0.89      0.89     49955